import { ITestimonial } from '@/types'
import { generateTestimonials } from './utils'

export const linkedInTestimonials: ITestimonial[] = [
  {
    author: {
      avatar: require('@/img/avatars/samuel-levens.jpeg').default.src,
      name: 'Samuel Levens',
      title: 'Software Engineer',
      company: 'Atlassian',
      linkedInUrl: 'https://www.linkedin.com/in/samuel-levens-24b1a896',
    },
    feedback: `Anish is a brilliant developer, mostly due to his attitude at approaching problems. Whenever we discussed problems the focus was on the solution and the steps we would need to take to get there. Able to explain complicated concepts succintly so we could create a strong understanding of the issue at hand. Anish has been one of the strongest team members I've worked with!`,
    date: '07/06/21, 12:22 AM',
    status: 'VISIBLE',
    relationship: 'COLLEAGUE',
  },
  {
    author: {
      avatar: require('@/img/avatars/luis-debourg.jpeg').default.src,
      name: 'Luis Debourg',
      title: 'Software Developer, UI/UX Designer',
      company: 'Office of Public Prosecutions, Victoria',
      linkedInUrl: 'https://www.linkedin.com/in/luisdebourgm',
    },
    feedback: `Anish has been an exceptional guide and mentor, and his expertise and dedication have had a profound impact on my growth in the field.  Throughout our mentorship relationship, I witnessed Anish’s exceptional knowledge and expertise in software development. His deep understanding of programming concepts, frameworks, and best practices made them an invaluable resource.   Beyond his technical skills, Anish possesses exceptional communication abilities. He effortlessly explained complex programming concepts in a way that was easily understandable, fostering my learning and comprehension.   I am especially grateful for the real-world insights and practical advice Anish shared with me. His experiences in the software development industry provided me with valuable perspectives on the industry's demands, trends, and career opportunities.`,
    date: '06/29/23, 12:59 PM',
    status: 'VISIBLE',
    relationship: 'MENTEE',
  },
  {
    author: {
      avatar: require('@/img/avatars/sepideh-montaser.jpeg').default.src,
      name: 'Sepideh Montaser',
      title: 'IT Support Specialist',
      company: 'Portable Systems Pty Ltd',
      linkedInUrl: 'https://www.linkedin.com/in/sepideh-montaser',
    },
    feedback: `I highly recommend Anish for the position of technical mentor. Anish is an exceptional communicator and possesses excellent interpersonal skills. He is patient, approachable, and attentive, making mentees feel comfortable seeking guidance and asking questions. He actively listens to mentees' concerns and challenges, providing constructive feedback and suggestions. Anish fosters a supportive and inclusive learning environment, encouraging mentees to explore their own ideas and approaches while offering guidance when necessary. Thank you for considering my recommendation. I believe that Anish would be an outstanding addition to your organization and contribute significantly to the growth and development of mentees.`,
    date: '06/20/23, 02:57 AM',
    status: 'VISIBLE',
    relationship: 'MENTEE',
  },
  {
    author: {
      avatar: '',
      name: '⚛️ Barad Ghimire',
      title: 'Software Engineer',
      company: 'CYDRAM',
      linkedInUrl: 'https://www.linkedin.com/in/baradghimire',
    },
    feedback: `If I had to describe Anish with one word, I’d cheat and say “multifaceted”.  He is a musician, an artist, a solutionist, a developer; and to me, he is a mentor. Some of these skills are seemingly on the opposite ends of a spectrum, yet somehow he manages to apply learnings from one discipline to find a solution in another.  His programming is every bit as creative and fine-tuned as his music. And his music is every bit as precise and calculated as his programming. From rhythm to algorithm, he puts an insane amount of effort into every little detail of his craft.  Finally, as a mentor, he is not just patient and understanding, but also always open to learn with his mentees.`,
    date: '08/23/20, 05:31 AM',
    status: 'VISIBLE',
    relationship: 'COLLEAGUE',
  },
  {
    author: {
      avatar: require('@/img/avatars/loris-campanile.jpeg').default.src,
      name: 'Loris Campanile',
      title: 'CEO & Founder',
      company: 'Recargo',
      linkedInUrl: 'https://www.linkedin.com/in/loris-campanile',
    },
    feedback: `Anish is a great software developer and a great problem solver. He is the most organised developer I have met and will make sure to get a functional design right on paper before coding. Anish also understands the importance of teamwork and knows how important it is when delivering complex projects. He is also a great human being and I always have a lot of fun when working with Anish.`,
    date: '05/01/19, 07:27 AM',
    status: 'VISIBLE',
    relationship: 'COLLEAGUE',
  },
  {
    author: {
      avatar: require('@/img/avatars/gayatri-raghavan.jpeg').default.src,
      name: 'Gayatri Raghavan',
      title: 'Software Development Consultant',
      company: 'Shine Solutions Group',
      linkedInUrl: 'https://www.linkedin.com/in/gayatri-raghavan-044323111',
    },
    feedback: `Anish is one of the best team players I have had the pleasure of working with. He is very quick in picking up technologies and requirements. He has a very positive spirit, can-do attitude and is internally driven at work. He is also a great mentor and has helped junior team members by conducting knowledge transfer sessions, while delivering all his work on time.  He is also an excellent guitarist and a caricature artist who can make your day at work fun! Anish is a great asset to have in a team and I look forward to working with him again! I will definitely miss working with you Anish.`,
    date: '06/11/19, 06:46 AM',
    status: 'VISIBLE',
    relationship: 'COLLEAGUE',
  },
  {
    author: {
      avatar: require('@/img/avatars/ju-sun.jpeg').default.src,
      name: 'Ju (Jenny) Sun',
      title: 'Support and SRE',
      company: 'ANZ',
      linkedInUrl: 'https://www.linkedin.com/in/ju-jenny-sun',
    },
    feedback: `Anish is my industry mentor when I was in the Vic Digital Programme. I am very impressed by his professional skills as well as positive personality. During the three mentoring sessions, he gave me very useful interview skills, which helped me a lot during the interview. As a very experienced senior in the IT filed, he provided me with useful pre-onboarding tips, making myself well prepared and not worried when I started on my first day. Anish is an awesome mentor and I will definitely keep the connection with him!`,
    status: 'VISIBLE',
    relationship: 'MENTEE',
  },
  {
    author: {
      avatar: require('@/img/avatars/bruno-gatiba.jpeg').default.src,
      name: 'Bruno Gatiba',
      title: 'Mobile App Developement',
      company: 'Bring Back Australia',
      linkedInUrl: 'https://www.linkedin.com/in/bruno-gatiba-b8bb6b182',
    },
    feedback: `I had the pleasure of being mentored by Anish . He was exceptional an exceptional mentor who has played a critical role in shaping my career as a software engineer. During my mentorship period, he demonstrated a commitment to helping me grow both personally and professionally. He took the time to understand my strengths and weaknesses and provided me with valuable feedback and guidance on how to improve my skills.  I highly recommend Anish as a mentor to anyone seeking to grow their career in software engineering. He has been an invaluable resource to me and I am grateful for the opportunity to learn from him.`,
    date: '04/03/23, 12:36 AM',
    status: 'VISIBLE',
    relationship: 'MENTEE',
  },
  {
    author: {
      avatar: require('@/img/avatars/sam-bradbury.jpeg').default.src,
      name: 'Sam Bradbury',
      title: 'Web Developer',
      company: 'Section Media',
      linkedInUrl: 'https://www.linkedin.com/in/sam-bradbury-67694b87',
    },
    feedback: `Anish is an exceptional professional who is dedicated to helping others achieve their goals. As a mentor, Anish   has a wealth of knowledge and experience to share with others, and they are always willing to go above and beyond to help their mentees succeed. The advice I received was invaluable, putting me on track to finding the work that I desire. Anish was excellent with communicating his own experience and making it relatable to myself.   In short, I would highly recommend Anish as a mentor to anyone looking for guidance, support, and expertise in their field.`,
    date: '03/08/23, 10:36 AM',
    status: 'VISIBLE',
    relationship: 'MENTEE',
  },
  {
    author: {
      avatar: require('@/img/avatars/willwin-wang.jpeg').default.src,
      name: 'Willwin Wang',
      title: 'Staff Software Engineer',
      company: 'Seer',
      linkedInUrl: 'https://www.linkedin.com/in/willwinwang',
    },
    feedback: `Anish was a humble, attentive and was always interested to learn from others. He was easy to work with and was happy to help others. I highly recommend Anish for any of his future roles.`,
    date: '05/12/22, 08:55 PM',
    status: 'VISIBLE',
    relationship: 'COLLEAGUE',
  },
  {
    author: {
      avatar: require('@/img/avatars/melani-arachchige.jpeg').default.src,
      name: 'Melani Arachchige',
      title: 'Sales Coordinator, Administrator ',
      company: 'EMD Fencing Pty Ltd',
      linkedInUrl: 'https://www.linkedin.com/in/melani-arachchige-43838526',
    },
    feedback: `Anish has been mentoring me on my Digital Job Program.  As a beginner to web development industry, I have learnt tons of valuable advices and strategies from him. He is detail-oriented, patient, understanding, incredibly knowledgeable and having passionate for mentoring students.  He played an integral role in my three mentor sessions by encouraging me in building up my confidence towards get in to the industry.  Advices that he gave me in the terms of creating GItHub portfolio, documentations, building up networks and  implementing showcase of projects were immensely helpful. I am so glad to have Anish as my mentor and highly recommend him.`,
    date: '03/05/23, 11:48 AM',
    status: 'VISIBLE',
    relationship: 'MENTEE',
  },
  {
    author: {
      avatar: require('@/img/avatars/gloria-han.jpeg').default.src,
      name: 'Gloria Han',
      title: 'Web Developer',
      company: 'Solar Power Outlet',
      linkedInUrl: 'https://www.linkedin.com/in/gloria-han-b6698b127',
    },
    feedback: `Anish is a very helpful mentor. He gave me tons of good advice and helped me modify my resume and portfolio in detail, word by word. I really learned a lot from him. I got promoted after 3 times mentoring. So glad to meet him. highly recommend Anish to be your mentor.`,
    date: '02/28/23, 03:19 AM',
    status: 'VISIBLE',
    relationship: 'MENTEE',
  },
  {
    author: {
      avatar: require('@/img/avatars/max-salubritsky.jpeg').default.src,
      name: 'Max Salubritsky',
      title: 'Junior Full-stack Web Developer ',
      company: 'Traffio',
      linkedInUrl: 'https://www.linkedin.com/in/salumaxx',
    },
    feedback: `Anish was my mentor when I participated in the Digital Job Victoria Program and I am grateful to him for his insights and help during our sessions. As a full-time full-stack developer now, I can genuinely recommend Anish as a knowledgeable and caring mentor who will help mentees set up a clear plan to their success.`,
    date: '02/11/23, 10:22 PM',
    status: 'VISIBLE',
    relationship: 'MENTEE',
  },

  {
    author: {
      avatar: require('@/img/avatars/romain-endelin.jpeg').default.src,
      name: 'Romain Endelin',
      title: 'Senior Software Engineer in Test',
      company: 'Sweep',
      linkedInUrl: 'https://www.linkedin.com/in/romain-endelin',
    },
    feedback: `I had the pleasure to work with Anish in Zendesk.  Anish really loves engineering as a craft, and is excellent at it. He cares not just about good code, but about delivering a beautiful experience to the users. But I\'m also very grateful for his attitude towards less enjoyable tasks: "keep the light on", maintenance, reliability... He took these on courageously, and really helped our team get through.  I have also detected a mature, "leader without a title" attitude from Anish when it comes to continuously improving the team. Besides his maturity in process & delivery, he\'s also super fun to work with, and his enthusiasm was communicative in the team..`,
    date: '09/15/22, 12:39 PM',
    status: 'VISIBLE',
    relationship: 'COLLEAGUE',
  },
  {
    author: {
      avatar: require('@/img/avatars/valentin-carmignac.jpeg').default.src,
      name: 'Valentin Carmignac',
      title: 'Staff Software Engineer',
      company: 'Jane.app',
      linkedInUrl: 'https://www.linkedin.com/in/vcarmignac',
    },
    feedback: `Anish showed a lot of interest for frontend framework and design systems as soon as he joined Zendesk. He picked up new concepts quickly and became autonomous on those tasks. He is very comfortable leading meetings and give everyone a chance to communicate.  Beside his skills Anish is a humble and intelligent person. Working with him is a pleasure and I'm looking forward to see how he progresses in his career.   Keep up the good work!`,
    date: '03/07/22, 09:21 PM',
    status: 'VISIBLE',
    relationship: 'COLLEAGUE',
  },
  {
    author: {
      avatar: require('@/img/avatars/byron-aguirre-valencia.jpeg').default.src,
      name: 'Byron Aguirre Valencia',
      title: 'DevOps Engineer',
      company: 'NAB',
      linkedInUrl: 'https://www.linkedin.com/in/byron-a-bbb56b121',
    },
    feedback: `I was really fortunate in the beginnings of my career to work along side with Anish. I learnt a lot from him, apart from being an excellent colleague he also stand out as an excellent teacher always eager to share his knowledge, teach his methodologies for problem solving and from time to time his native language. During the time we worked together he displayed qualities of a gifted person in his artistic drawings, graphics design as well in his natural talent for music.`,
    date: '08/15/21, 12:21 PM',
    status: 'VISIBLE',
    relationship: 'COLLEAGUE',
  },
  {
    author: {
      avatar: require('@/img/avatars/gerard-holland.jpeg').default.src,
      name: 'Gerard Holland',
      title: 'Chief Executive Officer',
      company: 'InternMatch.io',
      linkedInUrl: 'https://www.linkedin.com/in/gerardholland',
    },
    feedback: `Anish joined us as a junior software developer and soon became an integral part of the team.  One of those people that you think about when asking the question "who would we hate to lose?".  Anish created an enormous amount of value for our technology stack and business, but, more importantly, is an amazing human being that helped create the culture of our business.`,
    date: '07/18/21, 04:21 AM',
    status: 'VISIBLE',
    relationship: 'COLLEAGUE',
  },
  {
    author: {
      avatar: require('@/img/avatars/cyrus-shrestha.jpeg').default.src,
      name: 'Cyrus Shrestha',
      title: 'Javascript Developer',
      company: 'Outcome.Life',
      linkedInUrl: 'https://www.linkedin.com/in/cyrusshrestha',
    },
    feedback: `Anish is a very talented and resourceful developer. During the time we worked together he has always been very helpful and delivered on my requests on time.  His communication skills to communicate with higher management and colleagues is excellent. His arsenal of knowledge is vast and his understanding of both Front end and Back end makes him very easy to work with. His solution oriented mindset helps to drive the whole team forward. Successfully leading the back end team building a complicated back end driven system speaks for itself when it comes to his leadership. I am certain he will be a great addition to every team.`,
    date: '07/15/21, 12:44 AM',
    status: 'VISIBLE',
    relationship: 'COLLEAGUE',
  },
  {
    author: {
      avatar: require('@/img/avatars/dixanta-bahadur-shrestha.jpeg').default
        .src,
      name: 'Dixanta Bahadur Shrestha',
      title: 'Owner',
      company: 'Creators Institute of Business & Technology',
      linkedInUrl: 'https://www.linkedin.com/in/dixanta',
    },
    feedback: `A guy with a strong listening skills definitely added capability was himself a good guitarist too, I must say you should listen to him when he plays, straight from the heart. Now come to this programming skills a scholarship won guys for upgrading skills on the Programming, made later career on Software Engineering skills at a company where he sharpened his skills further up. After speaking with his colleagues/bosses, the impression he has made, I must say he is the one what every company requires for further progress. Wish you all the best for proving and pushing this far. I #Salute for your #deeds. Keep rocking, Keep Shining. All the best.  Regards`,
    date: '07/10/21, 11:57 AM',
    status: 'VISIBLE',
    relationship: 'COLLEAGUE',
  },

  {
    author: {
      avatar: require('@/img/avatars/jian-li.jpeg').default.src,
      name: 'Jian LI',
      title: 'Senior DevOps',
      company: 'Gada Technology Pty Ltd',
      linkedInUrl: 'https://www.linkedin.com/in/jianjackli',
    },
    feedback: `Worked with Anish for 1 year, he performed as full stack engineer(Java based) in the team, had good knowledge of Web Development including Javascript, Typescript, React.js, Node.js, Redux.js.   We worked together quite often to solve problems and exchange ideas about MySQL query optimizations, Docker application improvement.   From my side of view, he is the key player in the team and contribute a lot to projects, members had good time with him, wish you all the best Anish!`,
    date: '07/01/21, 12:53 AM',
    status: 'VISIBLE',
    relationship: 'COLLEAGUE',
  },
  {
    author: {
      avatar: require('@/img/avatars/adam-crow.jpeg').default.src,
      name: 'Adam Crow',
      title: 'Executive Chairman',
      company: 'Rolefy',
      linkedInUrl: 'https://www.linkedin.com/in/adamcrow',
    },
    feedback: `Anish worked for me for 4 years. He was an excellent developer and staff member. Anish took on challenges and mastered them. He was also superb at mentoring our new and junior employees in a number of areas, whether it was explaining the architecture, learning to develop using workflows and rules, java, and many other areas. Anish helped us so much in establishing our new Nepalese office. We appreciated his efforts and look forward to seeing his achievements to come. All the best Anish! You are a gun!`,
    date: '06/26/21, 04:50 AM',
    status: 'VISIBLE',
    relationship: 'COLLEAGUE',
  },
  {
    author: {
      avatar: require('@/img/avatars/kanika-gulati.jpeg').default.src,
      name: 'Kanika Gulati',
      title: 'Senior Software Engineer',
      company: 'SSP Limited',
      linkedInUrl: 'https://www.linkedin.com/in/kanika-gulati-a28a27143',
    },
    feedback: `As a team member, Anish earns my highest recommendation. When I joined GADA Technology, he helped me a lot in getting up to speed with the internal processes and the system. He is very talented and always has straight forward solutions to the most difficult  problems. Anyone would be lucky to have Anish as a mentor as he goes out of his way to provide you with the help and guidance you need.`,
    date: '06/21/20, 09:46 AM',
    status: 'VISIBLE',
    relationship: 'COLLEAGUE',
  },
  {
    author: {
      avatar: require('@/img/avatars/alwy-christyo.jpeg').default.src,
      name: 'Alwy Christyo',
      title: 'Senior Frontend Developer',
      company: 'Origin Energy',
      linkedInUrl: 'https://www.linkedin.com/in/alwychristyo',
    },
    feedback: `Anish is - in every sense of the word, professional. During my time working under his supervision, he has always been determined and highly disciplined. He helps his juniors a lot while still delivering features on time. If you want something to be done and to be done right, Anish would be the solid choice.`,
    date: '05/12/19, 10:18 AM',
    status: 'VISIBLE',
    relationship: 'COLLEAGUE',
  },
  {
    author: {
      avatar: require('@/img/avatars/sudan-shrestha.jpeg').default.src,
      name: 'Sudan Shrestha',
      title: 'Software Engineer',
      company: 'Reveal Group',
      linkedInUrl: 'https://www.linkedin.com/in/sudan-shrestha',
    },
    feedback: `It was great experience working with Anish at Gada Technology. He is experienced software developer with exceptional technical skills and also a great  team player. His can do attitude and multi tasking ability has always helped our team to meet the deadlines and deliver quality product on time. The other important part of Anish is, he was our in-house guitarist and made our Friday evenings fun and musical by playing gigs after works at the office.  He is multi talented and a valuable member to a team. I give him my full recommendation.`,
    date: '05/04/19, 06:03 AM',
    status: 'VISIBLE',
    relationship: 'COLLEAGUE',
  },
  {
    author: {
      avatar: require('@/img/avatars/rahul-samaranayake.jpeg').default.src,
      name: 'Rahul Samaranayake',
      title: 'Software Engineer',
      company: 'Zendesk',
      linkedInUrl: 'https://www.linkedin.com/in/rahul-samaranayake-981a9315b',
    },
    feedback: `Anish has taught me a lot about Java and Business Drools. I have has the opportunity to work with him on a variety of projects and it has been a pleasure working with him. When I joined GADA technology he trained me thoroughly.`,
    date: '05/01/19, 06:38 AM',
    status: 'VISIBLE',
    relationship: 'COLLEAGUE',
  },
  {
    author: {
      avatar: require('@/img/avatars/jayavani-swaminathan.jpeg').default.src,
      name: 'Jayavani Swaminathan',
      title: 'Senior Consultant',
      company: 'Infosys Ltd',
      linkedInUrl: 'https://www.linkedin.com/in/jayavani-swaminathan-52042610',
    },
    feedback: `It has been a pleasure working with Anish. He has proved himself to be an extremely competent and proactive IT professional.  Anish provides excellent technical solutions, understands the requirements quickly and supports the team. I look forward to my next opportunity to work with Anish.`,
    date: '05/01/19, 06:36 AM',
    status: 'VISIBLE',
    relationship: 'COLLEAGUE',
  },
  {
    author: {
      avatar: require('@/img/avatars/javed-shaik.jpeg').default.src,
      name: 'Javed Shaik',
      title: 'Social Media Coordinator',
      company: 'Superist',
      linkedInUrl: 'https://www.linkedin.com/in/javed-shaik',
    },
    feedback: `Anish had been a valuable asset and a team player who could come up with creative solutions for complex problems. He is always ready to learn something new in much less time than expected and add value to the teams.`,
    date: '07/19/21, 09:19 AM',
    status: 'VISIBLE',
    relationship: 'COLLEAGUE',
  },
  {
    author: {
      avatar: require('@/img/avatars/sandeep-singh.jpeg').default.src,
      name: 'Sandeep Singh',
      title: 'Python Developer / Software Programmer',
      linkedInUrl: 'https://www.linkedin.com/in/baradghimire',
    },
    feedback: `Anish Maharjan has been an exceptional mentor during my time as an InternMatch mentee. His guidance, expertise, and support have been invaluable in shaping my professional growth. I highly recommend him for his outstanding mentorship abilities.`,
    date: '06/21/23, 12:51 AM',
    status: 'VISIBLE',
    relationship: 'MENTEE',
  },
  {
    author: {
      avatar: require('@/img/avatars/josh-mackay.jpeg').default.src,
      name: 'Josh MacKay',
      title: 'Front End Development ',
      linkedInUrl: 'https://www.linkedin.com/in/joshmackay',
    },
    feedback: `I recently received mentoring from Anish related to my career pursuits as a web developer.  Anish provided me with a lot of useful information and assistance particularly with laying the foundation of my online presence and technical skills that I need to focus on to stand out. Anish was very realistic and did not sugar coat anything, he was upfront about the competitive climate and used that as the context for the advice that he provided.  Coming from a background that didn't really rely on Linkedin, Anish was able to reframe the way that I think about the platform and use it to my advantage.  While we only had a few sessions together, they were very valuable and I believe they have set me up to have more confidence in pursuing my goals.`,
    date: '06/29/23, 12:59 PM',
    status: 'VISIBLE',
    relationship: 'MENTEE',
  },
  {
    author: {
      avatar: require('@/img/avatars/srinivas-chaparala.jpeg').default.src,
      name: 'Srinivas Chaparala',
      title: 'Assistant Instructor',
      company: 'Academy Xi',
      linkedInUrl: 'https://www.linkedin.com/in/srinivas-chaparala',
    },
    feedback: `Anish has been serving as my mentor during my transition into a web development career, consistently exhibiting a high level of preparation for our mentoring sessions. His structured and well-planned approach to these sessions has significantly contributed to my enhanced understanding of the industry. Anish concludes each session with a comprehensive session summary and follow-up tasks that he addresses during our subsequent meeting. Without reservation, I strongly endorse him as a mentor for any aspiring developer.`,
    date: '02/11/23, 05:11 PM',
    status: 'VISIBLE',
    relationship: 'MENTEE',
  },
  {
    author: {
      avatar: require('@/img/avatars/udani-wijesinghe.jpeg').default.src,
      name: 'Udani Wijesinghe',
      title: 'Software Tester',
      company: 'Gada Technology Pty Ltd',
      linkedInUrl: 'https://www.linkedin.com/in/udani-wijesinghe',
    },
    feedback: `I have the pleasure of working with Anish in Gada Technology (pty) Ltd. He is one of the key resources in the development team. He has the ability to work under tremendous pressure to meet deadlines and achieve client satisfaction. He is a very friendly individual with a can-do attitude which helps the team to achieve their goals. He always willingly accepts challenging assignments and offers to contribute wherever he can. He has demonstrated excellent programming and analytical skills, which are essential to address the constantly evolving client’s business requirements. He is an asset to any team in which he works, and I would highly recommend him to any organization for their betterment.`,
    date: '07/01/21, 10:52 PM',
    status: 'VISIBLE',
    relationship: 'COLLEAGUE',
  },
  {
    author: {
      avatar: require('@/img/avatars/debbie-corbett.jpeg').default.src,
      name: 'Debbie Corbett',
      title: 'Team lead, design systems',
      company: 'Canva',
      linkedInUrl: 'https://www.linkedin.com/in/debcorbett',
    },
    feedback: `Thanks Anish for always being such an outstanding engineering partner to the design organisation at Zendesk.  Whenever I work with Anish on a design related problem, he jumps in to understand it, and comes back with thoughtful questions and helpful improvements. He always goes the extra mile, picking up spacing and padding errors and fixing them – always making sure we are creating high quality interfaces for our customers.  Anish is able to translate high level engineering concepts to a design audience, showing high levels of empathy and emotional intelligence. The importance of this skill can not be underestimated in a complex product environment. This skill and mindset helps us collaborate in a cross functional team to achieve great outcomes.   Anish is also generous with teaching others and sharing his knowledge, and has been a mentor to me in the space of front end engineering.  Thank you for your hard work and dedication Anish!`,
    date: '08/08/22, 02:19 AM',
    status: 'VISIBLE',
    relationship: 'COLLEAGUE',
  },
]

export const testimonials = generateTestimonials(linkedInTestimonials)
